const viewer=document.querySelector('#viewer'),select=document.querySelector('#location'),hotspot=document.querySelector('.hotspot'),pointLabel=document.querySelector('.label:not(.area-label)'),areaLabel=document.querySelector('.area-label'),overlay=document.querySelector('#areaOverlay'),polygon=overlay.querySelector('polygon');
let library,current='endocrine',areaEls=[];
const views={front:{orbit:'180deg 75deg 105%',target:'0m 0m 0m',fov:'30deg'},endocrine:['166deg 80deg 61%','25deg'],sympathetic:['190deg 68deg 62%','24deg'],subcortex:['150deg 84deg 62%','24deg'],thalamus:['145deg 82deg 58%','23deg'],adrenal:['168deg 80deg 61%','24deg'],brain:['145deg 83deg 58%','23deg'],pointZero:['180deg 74deg 60%','24deg'],mouth:['190deg 82deg 60%','24deg'],shoulder:['205deg 78deg 62%','24deg'],cervicalSpine:['160deg 80deg 60%','24deg'],occiput:['140deg 82deg 70%','24deg'],earApex:['180deg 42deg 80%','22deg']};
const human=id=>id==='earApex'?'Ear Apex':library.lockedPoints[id]?.name||library.areas[id]?.name;
function target(s){return s.trim().split(/\s+/).slice(0,3).join(' ')}
function applyView(id){const item=library.lockedPoints[id]||library.areas[id],v=views[id];viewer.cameraTarget=target(item.position||item.centerPosition);viewer.cameraOrbit=v[0];viewer.fieldOfView=v[1]}
function clearArea(){areaEls.forEach(e=>e.remove());areaEls=[];overlay.classList.remove('visible');areaLabel.classList.remove('visible')}
function makeArea(area){clearArea();hotspot.classList.remove('visible');pointLabel.classList.remove('visible');viewer.updateHotspot({name:'hotspot-area-center',position:area.centerPosition,normal:area.centerNormal});viewer.updateHotspot({name:'hotspot-area-label',position:area.centerPosition,normal:area.centerNormal});areaLabel.textContent=area.name;areaLabel.classList.add('visible');area.boundaryPoints.forEach((p,i)=>{const b=document.createElement('button');b.className='area-anchor';b.slot=`hotspot-boundary-${i}`;b.dataset.position=p.position;b.dataset.normal=p.normal;b.setAttribute('aria-hidden','true');viewer.appendChild(b);areaEls.push(b)});requestOverlay()}
function choose(id,focus=true){current=id;select.value=id;const point=library.lockedPoints[id],area=library.areas[id];document.querySelector('#name').textContent=human(id);document.querySelector('#type').textContent=point?'Point':'Area';document.querySelector('#guidance').textContent=point?'The selected point is highlighted in Bloomé burgundy.':'The selected region is shown as a translucent Bloomé highlight.';if(point){clearArea();viewer.updateHotspot({name:'hotspot-selected',position:point.position,normal:point.normal});viewer.updateHotspot({name:'hotspot-selected-label',position:point.position,normal:point.normal});pointLabel.textContent=point.name;hotspot.classList.add('visible');pointLabel.classList.add('visible')}else makeArea(area);if(focus)applyView(id)}
function center(el){const r=el.getBoundingClientRect(),s=document.querySelector('.stage').getBoundingClientRect();return r.width?[(r.left+r.width/2-s.left),(r.top+r.height/2-s.top)]:null}
let raf;function requestOverlay(){cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{if(!library?.areas[current])return;const stage=document.querySelector('.stage'),r=stage.getBoundingClientRect(),pts=areaEls.map(center).filter(Boolean);overlay.setAttribute('viewBox',`0 0 ${r.width} ${r.height}`);polygon.setAttribute('points',pts.map(p=>p.join(',')).join(' '));overlay.classList.toggle('visible',pts.length>2)})}
fetch('./data/coordinates-1b10-frozen.json').then(r=>r.json()).then(data=>{library=data;const groups=[['Points',data.lockedPoints],['Areas',data.areas]];groups.forEach(([label,obj])=>{const g=document.createElement('optgroup');g.label=label;Object.keys(obj).forEach(id=>g.append(new Option(human(id),id)));select.append(g)});const start=()=>{document.body.classList.remove('is-loading');const requested=new URLSearchParams(location.search).get('location');choose((data.lockedPoints[requested]||data.areas[requested])?requested:'endocrine')};if(viewer.loaded)start();else viewer.addEventListener('load',start,{once:true});select.addEventListener('change',()=>{choose(select.value);const url=new URL(location.href);url.searchParams.set('location',select.value);history.replaceState({},'',url)})}).catch(()=>{document.body.classList.remove('is-loading');document.querySelector('#loadError').hidden=false});
viewer.addEventListener('camera-change',requestOverlay);viewer.addEventListener('progress',e=>viewer.querySelector('.progress i').style.transform=`scaleX(${e.detail.totalProgress})`);viewer.addEventListener('error',()=>{document.body.classList.remove('is-loading');document.querySelector('#loadError').hidden=false});window.addEventListener('resize',requestOverlay);document.querySelector('#focus').onclick=()=>applyView(current);document.querySelector('#front').onclick=()=>{viewer.cameraTarget=views.front.target;viewer.cameraOrbit=views.front.orbit;viewer.fieldOfView=views.front.fov};document.querySelector('#reset').onclick=()=>applyView(current);
